
import os
import logging
import google.generativeai as genai
from typing import Optional

logger = logging.getLogger(__name__)

def configure_gemini(api_key: str):
    """Configure the Gemini API with the provided key."""
    if not api_key:
        return
    genai.configure(api_key=api_key)

def analyze_and_select(image_bytes: bytes, prompt: str, context: str = ""):
    """
    Analyze the image grid using Gemini 1.5 Pro and select the best match.
    
    Args:
        image_bytes: The image data in bytes.
        prompt: The original prompt used to generate the image.
        context: Optional story or thematic context to guide selection.
        
    Returns:
        tuple: (selected_quadrant_int, reasoning_str)
    """
    try:
        # Using Gemini 3 Flash Preview - the absolute latest frontier model
        model = genai.GenerativeModel('gemini-3-flash-preview')
        
        # Construct the prompt for Gemini
        analysis_prompt = f"""
        You are an expert art director and visual storyteller.
        I will show you a 2x2 grid of 4 images generated by Midjourney.
        
        Original User Prompt: "{prompt}"
        
        Director's Selection Criteria / Context:
        ---
        "{context if context else 'Pick the most visually striking and high-quality image.'}"
        ---
        
        Task:
        1. Analyze the 4 images in the grid (Quadrant 1 is Top-Left, 2 is Top-Right, 3 is Bottom-Left, 4 is Bottom-Right).
        2. Select the single image that BEST captures the essence of the prompt and the provided criteria.
        
        SAFEGUARD AGAINST REJECTION:
        - If the director's criteria contains strict "REJECT" rules and NO image perfectly matches every single one, you MUST still pick the ONE image that is the CLOSEST match or violates the rules the least. 
        - DO NOT refuse to make a selection. One of the 4 quadrants MUST be selected.
        - Prioritize character consistency (hair/eyes/clothes) first, then aesthetic quality.
        
        Return your response in this exact format:
        SELECTED: [number 1-4]
        REASONING: [one brief sentence explaining specifically why this image was the best or closest match among the four]
        """
        
        # Prepare content parts
        cookie_picture = {
            'mime_type': 'image/png',
            'data': image_bytes
        }
        
        response = model.generate_content([analysis_prompt, cookie_picture])
        
        if response and response.text:
            text = response.text.replace('*', '').strip()
            # Extract number
            import re
            num_match = re.search(r'(?:SELECTED:\s*)?([1-4])', text, re.IGNORECASE)
            
            if num_match:
                selected = int(num_match.group(1))
                # Extract reasoning
                reasoning_match = re.search(r'REASONING:\s*(.*)', text, re.IGNORECASE | re.DOTALL)
                reasoning = reasoning_match.group(1).strip() if reasoning_match else "Best match for prompt."
                
                logger.info(f"AI Selected Quadrant: {selected} | Reasoning: {reasoning}")
                return selected, reasoning
            
        logger.warning(f"AI failed to return a valid number. Response: {response.text if response else 'None'}")
        return 0, "No selection made."
        
    except Exception as e:
        logger.error(f"Error in AI analysis: {e}")
        return 0, f"Error: {str(e)}"


def enhance_video_prompt(base_prompt: str) -> str:
    """
    Use Gemini to expand a simple prompt into a rich, cinematic video prompt.
    """
    try:
        model = genai.GenerativeModel('gemini-3-flash-preview')
        
        system_instructions = """
        You are a cinematic prompt engineer for Midjourney Video.
        Your goal is to transform a short, simple prompt into a detailed, visually evocative video script prompt.
        
        GUIDELINES:
        - Maintain the user's original core subject and intent.
        - Add cinematic terminology (e.g., 'drone shot', 'bokeh', 'volumetric lighting', '8k', 'photorealistic').
        - Describe movement and atmosphere (e.g., 'swirling mist', 'gently swaying trees', 'shimmering reflections').
        - Keep the prompt concise but descriptive (approx 30-50 words).
        - DO NOT add Midjourney parameters like --ar or --v (those are handled elsewhere).
        - Return ONLY the enhanced prompt text.
        """
        
        response = model.generate_content([system_instructions, f"Original Prompt: {base_prompt}"])
        
        if response and response.text:
            enhanced = response.text.replace('Enhanced Prompt:', '').replace('*', '').strip()
            return enhanced
            
        return base_prompt
    except Exception as e:
        logger.error(f"Error enhancing prompt: {e}")
        return base_prompt
